services:
  discord-bot:
    build: .
    ports:
      - '80:80'
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GUILD_ID=${GUILD_ID}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
      - NOTION_READER_DATABASE_ID=${NOTION_READER_DATABASE_ID}
      - NOTION_FEEDS_DATABASE_ID=${NOTION_FEEDS_DATABASE_ID}
